# The commit to deploy.
commit: master

# The git repository to clone when deploying.
git_repo: https://github.com/bocoup/image-annotator.git

# Get secrets from vault, or an empty dictonary if we don't need them.
# Note that the `vault` variable is typically populated by secrets.yml
secrets: "{{vault | default({})}}"

# Control environment variables for each supported environment.
env_vars:
  development:
    PGHOST: localhost
    PGPORT: 5432
    PGNAME: image-annotator
    PGUSER: image-annotator
    PGPASSWORD:
    NODE_ENV: development
    HTTP_HOST: 0.0.0.0
    HTTP_PORT: 8000
  production:
    PGHOST: localhost
    PGPORT: 5432
    PGNAME: image-annotator
    PGUSER: image-annotator
    PGPASSWORD: "{{secrets.PGPASSWORD | default(None)}}"
    NODE_ENV: production
    HTTP_HOST: localhost
    HTTP_PORT: 8000
  staging:
    PGHOST: localhost
    PGPORT: 5432
    PGNAME: image-annotator
    PGUSER: image-annotator
    # this complex variable assignment makes it so ansible's head doesn't
    # explode when a vault variable isn't defined (e.g. when provisioning
    # a local vagrant machine where vault isn't needed)
    PGPASSWORD: "{{secrets.PGPASSWORD | default(None)}}"
    NODE_ENV: production
    HTTP_HOST: localhost
    HTTP_PORT: 8000

# Parent directory for cloned repository directories. The clone_path and
# site_path should be children of this directory.
base_path: /mnt

# Temporary location where git_repo will be cloned and the build scripts
# will be run before going live.
clone_path: "{{base_path}}/temp"

# Where the production site symlink will exist.
site_path: "{{base_path}}/site"

# The directory that nginx will serve as the production site.
public_path: "{{site_path}}/dist"

# Ownership for application and code.
user: ia
group: ia

# The hostname of the server this is deployed to.
hostname: image-annotator

# Keep this many previous deploys so we can roll back quickly if needed.
keep_n_most_recent: 3

# The s3 bucket for database backups.
backup_bucket: image-annotator-backup

# Manage authentication.
basic_auth: "{{env != 'development'}}"
basic_auth_users: "{{secrets.users | default([])}}"
basic_auth_password: kp7NlHvLFraLQ

# These variables control which domains nginx responds to.
# If a domain list is provided in an inventory file, nginx will
# use the first entry as the canonical and redirect all others
# to it. If no domain listing is provided it is assumed that the
# provided hostname in the inventory file is the only domain.
domains: "{{domain_list | default([inventory_hostname])}}"
canonical_domain: "{{domains.0}}"

# SSL cert location.
cert_path: "/etc/dehydrated/certs"
ssl_key_file: "privkey.pem"
ssl_cert_file: "fullchain.pem"
